-- TableGenerator.sql의 PostgreSQL 버전
-- 대상 PostgreSQL 데이터베이스에 연결한 후 이 스크립트를 실행하세요.
-- PostgreSQL은 MySQL의 USE 문을 지원하지 않습니다.

CREATE TABLE member (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    contact_number VARCHAR(30),
    street VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE manager (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE brand (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE product (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock INTEGER NOT NULL,
    category_id INTEGER,
    brand_id INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    FOREIGN KEY (category_id) REFERENCES category(id),
    FOREIGN KEY (brand_id) REFERENCES brand(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE shipping_info (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number VARCHAR(50),
    carrier VARCHAR(100),
    shipping_date DATE,
    delivery_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE purchase (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    shipping_info_id INTEGER,
    FOREIGN KEY (member_id) REFERENCES member(id),
    FOREIGN KEY (shipping_info_id) REFERENCES shipping_info(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE order_detail (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id INTEGER,
    product_id INTEGER,
    quantity INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (purchase_id) REFERENCES purchase(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE shopping_cart (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER,
    FOREIGN KEY (member_id) REFERENCES member(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE cart_item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_cart_id INTEGER,
    product_id INTEGER,
    quantity INTEGER NOT NULL,
    FOREIGN KEY (shopping_cart_id) REFERENCES shopping_cart(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE purchase_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER,
    purchase_id INTEGER,
    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES member(id),
    FOREIGN KEY (purchase_id) REFERENCES purchase (id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE comment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER,
    member_id INTEGER,
    comment TEXT NOT NULL,
    comment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'approved',
    manager_id INTEGER,
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (member_id) REFERENCES member(id),
    FOREIGN KEY (manager_id) REFERENCES manager(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE discount (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    discount_percentage DECIMAL(5, 2) NOT NULL,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE product_discount (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER,
    discount_id INTEGER,
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (discount_id) REFERENCES discount(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

-- 테이블 및 컬럼 주석 설명 문서
COMMENT ON TABLE member IS '고객 계정, 인증, 연락처 및 감사(Audit) 정보를 저장합니다.';
COMMENT ON COLUMN member.id IS '사용자의 고유 식별자.';
COMMENT ON COLUMN member.username IS '사용자 계정을 식별하는 데 사용되는 고유한 사용자 이름.';
COMMENT ON COLUMN member.password IS '사용자 계정과 관련된 비밀번호 인증 자격 증명.';
COMMENT ON COLUMN member.name IS '사용자의 이름.';
COMMENT ON COLUMN member.email IS '사용자 계정과 관련된 고유한 이메일 주소.';
COMMENT ON COLUMN member.contact_number IS '사용자의 연락처 전화번호.';
COMMENT ON COLUMN member.street IS '사용자의 도로명 주소.';
COMMENT ON COLUMN member.city IS '사용자 주소의 도시.';
COMMENT ON COLUMN member.state IS '사용자 주소의 주(State) 또는 도(Province).';
COMMENT ON COLUMN member.postal_code IS '사용자 주소의 우편번호.';
COMMENT ON COLUMN member.country IS '사용자 주소의 국가.';
COMMENT ON COLUMN member.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN member.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN member.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN member.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE manager IS '관리자 계정, 인증 및 감사(Audit) 정보를 저장합니다.';
COMMENT ON COLUMN manager.id IS '관리자의 고유 식별자.';
COMMENT ON COLUMN manager.username IS '관리자 계정을 식별하는 데 사용되는 고유한 사용자 이름.';
COMMENT ON COLUMN manager.password IS '관리자 계정과 관련된 비밀번호 인증 자격 증명.';
COMMENT ON COLUMN manager.email IS '관리자 계정과 관련된 고유한 이메일 주소.';
COMMENT ON COLUMN manager.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN manager.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN manager.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN manager.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE category IS '상품을 분류하는 데 사용되는 상품 카테고리를 저장합니다.';
COMMENT ON COLUMN category.id IS '카테고리의 고유 식별자.';
COMMENT ON COLUMN category.name IS '상품 카테고리의 고유 이름.';
COMMENT ON COLUMN category.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN category.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN category.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN category.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE brand IS '상품 브랜드 정보 및 브랜드 상태를 저장합니다.';
COMMENT ON COLUMN brand.id IS '브랜드의 고유 식별자.';
COMMENT ON COLUMN brand.name IS '브랜드의 고유 이름.';
COMMENT ON COLUMN brand.status IS '브랜드의 현재 상태: active(활성), inactive(비활성) 또는 old(이전).';
COMMENT ON COLUMN brand.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN brand.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN brand.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN brand.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE product IS '온라인 쇼핑 시스템에서 판매 가능한 상품을 저장합니다.';
COMMENT ON COLUMN product.id IS '상품의 고유 식별자.';
COMMENT ON COLUMN product.name IS '상품의 이름.';
COMMENT ON COLUMN product.description IS '상품에 대한 상세 설명.';
COMMENT ON COLUMN product.price IS '상품의 현재 단가.';
COMMENT ON COLUMN product.stock IS '현재 재고로 남아있는 상품의 수량.';
COMMENT ON COLUMN product.category_id IS '상품에 할당된 카테고리의 식별자.';
COMMENT ON COLUMN product.brand_id IS '상품과 연관된 브랜드의 식별자.';
COMMENT ON COLUMN product.status IS '상품의 현재 상태: active(활성) 또는 inactive(비활성).';
COMMENT ON COLUMN product.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN product.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN product.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN product.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE shipping_info IS '주문과 관련된 배송 및 인도 정보를 저장합니다.';
COMMENT ON COLUMN shipping_info.id IS '배송 정보의 고유 식별자.';
COMMENT ON COLUMN shipping_info.tracking_number IS '화물에 할당된 배송 추적 번호.';
COMMENT ON COLUMN shipping_info.carrier IS '배송 업체(택배사)의 이름.';
COMMENT ON COLUMN shipping_info.shipping_date IS '화물이 발송된 날짜.';
COMMENT ON COLUMN shipping_info.delivery_date IS '화물이 배송 완료된 날짜.';
COMMENT ON COLUMN shipping_info.status IS '현재 배송 상태: pending(대기 중), shipped(발송됨), delivered(배송 완료) 또는 returned(반품됨).';
COMMENT ON COLUMN shipping_info.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN shipping_info.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN shipping_info.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN shipping_info.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE purchase IS '고객 주문 정보, 주문 상태, 총액 및 배송 참조 정보를 저장합니다.';
COMMENT ON COLUMN purchase.id IS '주문의 고유 식별자.';
COMMENT ON COLUMN purchase.member_id IS '주문을 접수한 사용자의 식별자.';
COMMENT ON COLUMN purchase.order_date IS '주문이 생성된 날짜 및 시간.';
COMMENT ON COLUMN purchase.status IS '현재 주문 상태: pending(대기 중), processing(처리 중), shipped(발송됨), delivered(배송 완료), cancelled(취소됨) 또는 returned(반품됨).';
COMMENT ON COLUMN purchase.total_amount IS '주문의 총 결제 금액.';
COMMENT ON COLUMN purchase.shipping_info_id IS '주문과 관련된 배송 정보의 식별자.';
COMMENT ON COLUMN purchase.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN purchase.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN purchase.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN purchase.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE order_detail IS '고객 주문에 속한 개별 상품의 세부 품목(라인 아이템)을 저장합니다.';
COMMENT ON COLUMN order_detail.id IS '주문 상세 품목의 고유 식별자.';
COMMENT ON COLUMN order_detail.purchase_id IS '해당 세부 품목을 포함하는 주문의 식별자.';
COMMENT ON COLUMN order_detail.product_id IS '주문에 포함된 상품의 식별자.';
COMMENT ON COLUMN order_detail.quantity IS '주문한 상품의 수량.';
COMMENT ON COLUMN order_detail.price IS '주문 당시의 상품 단가.';
COMMENT ON COLUMN order_detail.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN order_detail.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN order_detail.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN order_detail.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE shopping_cart IS '사용자와 연관된 장바구니를 저장합니다.';
COMMENT ON COLUMN shopping_cart.id IS '장바구니의 고유 식별자.';
COMMENT ON COLUMN shopping_cart.member_id IS '장바구니를 소유한 사용자의 식별자.';
COMMENT ON COLUMN shopping_cart.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN shopping_cart.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN shopping_cart.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN shopping_cart.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE cart_item IS '장바구니에 담긴 상품과 수량을 저장합니다.';
COMMENT ON COLUMN cart_item.id IS '장바구니 품목의 고유 식별자.';
COMMENT ON COLUMN cart_item.shopping_cart_id IS '해당 품목을 포함하는 장바구니의 식별자.';
COMMENT ON COLUMN cart_item.product_id IS '장바구니에 담긴 상품의 식별자.';
COMMENT ON COLUMN cart_item.quantity IS '장바구니에 담긴 상품의 수량.';
COMMENT ON COLUMN cart_item.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN cart_item.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN cart_item.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN cart_item.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE purchase_history IS '사용자와 그들의 구매 주문 간의 관계를 저장합니다.';
COMMENT ON COLUMN purchase_history.id IS '구매 이력 레코드의 고유 식별자.';
COMMENT ON COLUMN purchase_history.member_id IS '구매와 연관된 사용자의 식별자.';
COMMENT ON COLUMN purchase_history.purchase_id IS '구매와 연관된 주문의 식별자.';
COMMENT ON COLUMN purchase_history.purchase_date IS '구매 이력 레코드가 생성된 날짜 및 시간.';
COMMENT ON COLUMN purchase_history.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN purchase_history.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN purchase_history.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN purchase_history.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE comment IS '사용자가 제출한 상품 댓글(리뷰) 및 그에 대한 검토(중재) 정보를 저장합니다.';
COMMENT ON COLUMN comment.id IS '댓글의 고유 식별자.';
COMMENT ON COLUMN comment.product_id IS '댓글이 작성된 상품의 식별자.';
COMMENT ON COLUMN comment.member_id IS '댓글을 제출한 사용자의 식별자.';
COMMENT ON COLUMN comment.comment IS '사용자가 작성한 댓글의 텍스트 내용.';
COMMENT ON COLUMN comment.comment_date IS '댓글이 제출된 날짜 및 시간.';
COMMENT ON COLUMN comment.status IS '댓글의 검토 상태: approved(승인됨) 또는 inappropriate(부적절함).';
COMMENT ON COLUMN comment.manager_id IS '댓글을 검토한 관리자의 식별자.';
COMMENT ON COLUMN comment.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN comment.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN comment.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN comment.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE discount IS '할인 정의 및 해당 유효 기간을 저장합니다.';
COMMENT ON COLUMN discount.id IS '할인의 고유 식별자.';
COMMENT ON COLUMN discount.name IS '할인의 이름.';
COMMENT ON COLUMN discount.description IS '할인에 대한 상세 설명.';
COMMENT ON COLUMN discount.discount_percentage IS '할인율(백분율 값).';
COMMENT ON COLUMN discount.start_date IS '할인이 적용되기 시작하는 날짜.';
COMMENT ON COLUMN discount.end_date IS '할인이 만료되는 날짜.';
COMMENT ON COLUMN discount.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN discount.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN discount.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN discount.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';

COMMENT ON TABLE product_discount IS '상품과 해당 상품에 적용할 수 있는 할인을 연결합니다.';
COMMENT ON COLUMN product_discount.id IS '상품-할인 연결 정보의 고유 식별자.';
COMMENT ON COLUMN product_discount.product_id IS '할인과 연관된 상품의 식별자.';
COMMENT ON COLUMN product_discount.discount_id IS '상품과 연관된 할인의 식별자.';
COMMENT ON COLUMN product_discount.created_at IS '레코드가 생성된 시간 기록.';
COMMENT ON COLUMN product_discount.updated_at IS '레코드가 마지막으로 수정된 시간 기록.';
COMMENT ON COLUMN product_discount.created_by IS '레코드를 생성한 사용자 또는 프로세스의 식별자.';
COMMENT ON COLUMN product_discount.updated_by IS '레코드를 마지막으로 수정한 사용자 또는 프로세스의 식별자.';
